---
# tasks file for software-repository
- name: load mos credentrials
  include_vars: mos-credentials.yml

- include: get-websession.yml

- name: download
  include: download.yml
  with_items:
    - siebel-{{target_platform}}-{{siebel_version}}
    - siebel-win-{{siebel_version}}
    - oracle-{{target_platform}}-{{oracle_version}}
    - oracle-client-{{target_platform}}-{{oracle_client_version}}
    - jdk-{{jdk_version}}
  loop_control:
    loop_var: product

- name: unarchive
  include: unarchive.yml
  with_items:
    - siebel-{{target_platform}}-{{siebel_version}}
    - siebel-win-{{siebel_version}}
    - oracle-{{target_platform}}-{{oracle_version}}
    - oracle-client-{{target_platform}}-{{oracle_client_version}}
    - jdk-{{jdk_version}}
  loop_control:
    loop_var: product

- name: install jdk
  include: install-jdk.yml
  when: ansible_distribution != "AIX"

- name: create siebel install image
  include: create-siebel-install-image.yml

- name: install nfs service
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - nfs-utils
  when: ansible_distribution != "AIX"

- name: export repository via nfs
  lineinfile:
    path: /etc/exports
    line: "{{ software_repository_path }}        *(rw)"
    create: yes
  when: ansible_distribution != "AIX"

- name: enable service nfs-server linux
  systemd:
    name: nfs-server
    enabled: yes
    state: restarted
  when: ansible_distribution != "AIX"
  
- name: export repository vio nfs on aix
  command: /usr/sbin/mknfsexp -d {{ software_repository_path }} -P -B -S "sys,krb5p,krb5i,krb5,dh" -t rw
  when: ansible_distribution == "AIX"
  
- name: create directory jce download dir
  file:
    path: "{{software_repository_path}}/jce/download"
    state: directory
    mode: 0755  

- name: get Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 8
  get_url:
    url: "http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip"
    tmp_dest: "{{software_repository_path}}"
    dest: "{{software_repository_path}}/jce/download"
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    timeout: 20
    force: no

- name: create directory jce unpack dir
  file:
    path: "{{software_repository_path}}/jce/unarchive"
    state: directory
    mode: 0755
  register: jce_upacked

- name: unarchive product jce
  unarchive:
    src: "{{software_repository_path}}/jce/download/jce_policy-8.zip"
    dest: "{{software_repository_path}}/jce/unarchive"
    remote_src: true
  when: jce_upacked.changed == true