---
# tasks file for siebel gateway

- name: create siebel_base
  file:
    path: "{{item}}"
    state: directory
    mode: 0775
    owner: siebel
    group: sse_role
  with_items:
    - "{{siebel_base_path}}"
    - "{{siebel_base_path}}/gw/oraInventory"
    - "{{siebel_base_path}}/sfs"

- name: create siebel gw oraInventory
  blockinfile:
    path: "{{siebel_base_path}}/gw/oraInventory/oraInst.loc"
    create: yes
    mode: 0775
    owner: siebel
    group: sse_role
    block: |
       inventory_loc={{siebel_base_path}}/gw/oraInventory
       inst_group=siebel

- name: template install gateway response file
  template: 
    src: roles/siebel-gateway/files/siebel-{{siebel_version}}-install-gw.rsp.j2
    dest: /tmp/siebel-{{siebel_version}}-install-gw.rsp

- name: install gateway
  shell : "source /home/siebel/.bash_profile && ./runInstaller -silent -waitforcompletion -responseFile /tmp/siebel-{{siebel_version}}-install-gw.rsp -jreloc {{java_home}} -invPtrLoc {{siebel_base_path}}/gw/oraInventory/oraInst.loc"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/Siebel_Install_Image/{{siebel_version}}/{{target_platform}}/Server/Siebel_Enterprise_Server/Disk1/install"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/gw/Siebel/gtwysrvr/cfgenv.sh"
    
- name: wait for tomcat to come up
  wait_for:
    port: 8092
    delay: 10
    state: started

- name: shutdown gateway
  shell : "{{siebel_base_path}}/gw/Siebel/applicationcontainer/bin/shutdown.sh"
  become: true
  become_user: siebel
  become_method: su
  args:
    executable: "/usr/bin/bash"

- name: wait for tomcat to stop
  wait_for:
    port: 8091
    delay: 10
    state: stopped

- name: move vanilla jre out of the way
  command: mv {{siebel_base_path}}/gw/Siebel/jre {{siebel_base_path}}/gw/Siebel/jre_orig
  args:
    creates: "{{siebel_base_path}}/gw/Siebel/jre_orig"

- name: link system jre
  file:
    src: "{{java_home}}/jre"
    dest: "{{siebel_base_path}}/gw/Siebel/jre"
    state: link

- name: start tomcat
  shell : "source /home/siebel/.bash_profile && {{siebel_base_path}}/gw/Siebel/applicationcontainer/bin/startup.sh"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{siebel_base_path}}/gw/Siebel/applicationcontainer"
    executable: "/usr/bin/bash"

- name: wait for tomcat to start
  wait_for:
    port: 8092
    delay: 10
    state: started
